/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LocoPixel (https://sketchfab.com/locopixel)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/no-mans-sky-radiant-pillar-bc1-97e9276d86454c92af42c50aefa8d405
Title: No Man’s Sky - Radiant Pillar BC1
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useMotion } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Ship(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/no_mans_sky_-_radiant_pillar_bc1.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
      console.log(animations);
    }
  }, [actions, animations]);

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 100 });

  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);

  useFrame(() => {
    group.current.position.y = ySpring.get();
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[Math.PI / 5, -3.1, -0.7]}
      scale={props.scale || -2.6}
      position={props.position || [-1.3, -10.9, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, -0.2, 2.2]}>
          <group name="1f570e8d69b84c71af7f8efe02dc5d3afbx">
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Radian_pillar_BC1"
                  position={[0.092, 73.322, -131.141]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.528, 1.161, 1]}
                >
                  <group name="Object_5" position={[101.36, -12.376, -31.042]}>
                    <mesh
                      name="Radian_pillar_BC1_special_red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_special_red_0.geometry}
                      material={materials.special_red}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metalic_dark_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_metalic_dark_0.geometry}
                      material={materials.metalic_dark}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_neutro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_metal_neutro_0.geometry}
                      material={materials.metal_neutro}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_neutro_0_1"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_metal_neutro_0_1.geometry
                      }
                      material={materials.metal_neutro}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_alumi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_metal_alumi_0.geometry}
                      material={materials.metal_alumi}
                    />
                    <mesh
                      name="Radian_pillar_BC1_Luz_azul_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_Luz_azul_0.geometry}
                      material={materials.Luz_azul}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_frio_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_metal_frio_0.geometry}
                      material={materials.metal_frio}
                    />
                    <mesh
                      name="Radian_pillar_BC1_Luz_allo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_Luz_allo_0.geometry}
                      material={materials.Luz_allo}
                    />
                    <mesh
                      name="Radian_pillar_BC1_blanco_especial_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_blanco_especial_0.geometry
                      }
                      material={materials.blanco_especial}
                    />
                    <mesh
                      name="Radian_pillar_BC1_Luz_verde_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_Luz_verde_0.geometry}
                      material={materials.Luz_verde}
                    />
                    <mesh
                      name="Radian_pillar_BC1_plastico_amarillo_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_plastico_amarillo_0.geometry
                      }
                      material={materials.plastico_amarillo}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_dorado_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_metal_dorado_0.geometry}
                      material={materials.metal_dorado}
                    />
                    <mesh
                      name="Radian_pillar_BC1_red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_red_0.geometry}
                      material={materials.material}
                    />
                    <mesh
                      name="Radian_pillar_BC1_plastico_negro_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_plastico_negro_0.geometry
                      }
                      material={materials.plastico_negro}
                    />
                    <mesh
                      name="Radian_pillar_BC1_plastico_gris_mate_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_plastico_gris_mate_0.geometry
                      }
                      material={materials.plastico_gris_mate}
                    />
                    <mesh
                      name="Radian_pillar_BC1_red_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_red_0_1.geometry}
                      material={materials.red_0}
                    />
                    <mesh
                      name="Radian_pillar_BC1_exa_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_exa_0.geometry}
                      material={materials.material_15}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_alumi_0_1"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_metal_alumi_0_1.geometry
                      }
                      material={materials.metal_alumi_0}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_frio_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_metal_frio_0_1.geometry}
                      material={materials.metal_frio_0}
                    />
                    <mesh
                      name="Radian_pillar_BC1_plastico_gris_brillo_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_plastico_gris_brillo_0.geometry
                      }
                      material={materials.plastico_gris_brillo}
                    />
                    <mesh
                      name="Radian_pillar_BC1_blanco_especial_0_1"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_blanco_especial_0_1.geometry
                      }
                      material={materials.blanco_especial_0}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metalic_dark_0_1"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_metalic_dark_0_1.geometry
                      }
                      material={materials.metalic_dark_0}
                    />
                    <mesh
                      name="Radian_pillar_BC1_Luz_roja_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Radian_pillar_BC1_Luz_roja_0.geometry}
                      material={materials.Luz_roja}
                    />
                    <mesh
                      name="Radian_pillar_BC1_metal_neutro_0_2"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Radian_pillar_BC1_metal_neutro_0_2.geometry
                      }
                      material={materials.metal_neutro_0}
                    />
                    <mesh
                      name="Radian_pillar_BC1_Material_#827_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes["Radian_pillar_BC1_Material_#827_0"].geometry
                      }
                      material={materials.Material_827}
                    />
                  </group>
                </group>
                <group
                  name="toma"
                  position={[-0.018, 149.78, -106.68]}
                  scale={[0.503, 0.503, 1]}
                >
                  <mesh
                    name="toma_metalic_dark_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.toma_metalic_dark_0.geometry}
                    material={materials.metalic_dark}
                  />
                </group>
                <group
                  name="open02"
                  position={[0.002, 136.652, 4.735]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[1.155, 1, 0.939]}
                >
                  <group name="Object_34" position={[0, -108.184, -64.758]}>
                    <mesh
                      name="open02_metal_alumi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_metal_alumi_0.geometry}
                      material={materials.metal_alumi}
                    />
                    <mesh
                      name="open02_vidrio_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_vidrio_0.geometry}
                      material={materials.vidrio}
                    />
                    <mesh
                      name="open02_plastico_negro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_plastico_negro_0.geometry}
                      material={materials.plastico_negro}
                    />
                    <mesh
                      name="open02_red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_red_0.geometry}
                      material={materials.material}
                    />
                    <mesh
                      name="open02_Luz_azul_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_Luz_azul_0.geometry}
                      material={materials.Luz_azul}
                    />
                    <mesh
                      name="open02_plastico_amarillo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_plastico_amarillo_0.geometry}
                      material={materials.plastico_amarillo}
                    />
                    <mesh
                      name="open02_metal_neutro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_metal_neutro_0.geometry}
                      material={materials.metal_neutro}
                    />
                    <mesh
                      name="open02_plastico_gris_brillo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_plastico_gris_brillo_0.geometry}
                      material={materials.plastico_gris_brillo}
                    />
                    <mesh
                      name="open02_Luz_verde_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open02_Luz_verde_0.geometry}
                      material={materials.Luz_verde}
                    />
                  </group>
                </group>
                <group
                  name="open01"
                  position={[0.013, 134.846, -31.09]}
                  rotation={[-0.611, 0, 0]}
                >
                  <group name="Object_45" position={[1.792, -14.889, -134.846]}>
                    <mesh
                      name="open01_metal_alumi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open01_metal_alumi_0.geometry}
                      material={materials.metal_alumi}
                    />
                    <mesh
                      name="open01_vidrio_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open01_vidrio_0.geometry}
                      material={materials.vidrio}
                    />
                    <mesh
                      name="open01_plastico_gris_brillo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open01_plastico_gris_brillo_0.geometry}
                      material={materials.plastico_gris_brillo}
                    />
                    <mesh
                      name="open01_plastico_amarillo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open01_plastico_amarillo_0.geometry}
                      material={materials.plastico_amarillo}
                    />
                    <mesh
                      name="open01_metal_neutro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open01_metal_neutro_0.geometry}
                      material={materials.metal_neutro}
                    />
                    <mesh
                      name="open01_special_red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open01_special_red_0.geometry}
                      material={materials.special_red}
                    />
                    <mesh
                      name="open01_plastico_negro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.open01_plastico_negro_0.geometry}
                      material={materials.plastico_negro}
                    />
                  </group>
                </group>
                <group
                  name="hidra"
                  position={[-0.052, 123.167, -23.098]}
                  rotation={[-1.691, 0, 0]}
                >
                  <group
                    name="Object_54"
                    position={[-13.66, -50.807, -134.693]}
                  >
                    <mesh
                      name="hidra_metal_alumi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.hidra_metal_alumi_0.geometry}
                      material={materials.metal_alumi}
                    />
                    <mesh
                      name="hidra_metal_neutro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.hidra_metal_neutro_0.geometry}
                      material={materials.metal_neutro}
                    />
                    <mesh
                      name="hidra_plastico_amarillo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.hidra_plastico_amarillo_0.geometry}
                      material={materials.plastico_amarillo}
                    />
                    <mesh
                      name="hidra_special_red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.hidra_special_red_0.geometry}
                      material={materials.special_red}
                    />
                    <mesh
                      name="hidra_metalic_dark_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.hidra_metalic_dark_0.geometry}
                      material={materials.metalic_dark}
                    />
                    <mesh
                      name="hidra_Luz_allo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.hidra_Luz_allo_0.geometry}
                      material={materials.Luz_allo}
                    />
                  </group>
                </group>
                <group
                  name="Base_hidra"
                  position={[-0.052, 102.707, -31.839]}
                  rotation={[-1.682, 0, 0]}
                >
                  <group
                    name="Object_62"
                    position={[-13.66, -64.563, -110.737]}
                  >
                    <mesh
                      name="Base_hidra_plastico_gris_brillo_0"
                      castShadow
                      receiveShadow
                      geometry={
                        nodes.Base_hidra_plastico_gris_brillo_0.geometry
                      }
                      material={materials.plastico_gris_brillo}
                    />
                    <mesh
                      name="Base_hidra_metal_alumi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Base_hidra_metal_alumi_0.geometry}
                      material={materials.metal_alumi}
                    />
                    <mesh
                      name="Base_hidra_plastico_gris_mate_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Base_hidra_plastico_gris_mate_0.geometry}
                      material={materials.plastico_gris_mate}
                    />
                    <mesh
                      name="Base_hidra_plastico_amarillo_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Base_hidra_plastico_amarillo_0.geometry}
                      material={materials.plastico_amarillo}
                    />
                    <mesh
                      name="Base_hidra_metalic_dark_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Base_hidra_metalic_dark_0.geometry}
                      material={materials.metalic_dark}
                    />
                    <mesh
                      name="Base_hidra_metal_neutro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Base_hidra_metal_neutro_0.geometry}
                      material={materials.metal_neutro}
                    />
                  </group>
                </group>
                <group
                  name="motor3"
                  position={[102.605, 70.699, -112.56]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group
                    name="Object_70"
                    position={[53.862, -185.691, -70.699]}
                  >
                    <mesh
                      name="motor3_metal_frio_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor3_metal_frio_0.geometry}
                      material={materials.metal_frio}
                    />
                    <mesh
                      name="motor3_metal_alumi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor3_metal_alumi_0.geometry}
                      material={materials.metal_alumi}
                    />
                    <mesh
                      name="motor3_metalic_dark_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor3_metalic_dark_0.geometry}
                      material={materials.metalic_dark}
                    />
                    <mesh
                      name="motor3_metal_neutro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor3_metal_neutro_0.geometry}
                      material={materials.metal_neutro}
                    />
                  </group>
                </group>
                <group
                  name="motor4"
                  position={[-102.605, 70.699, -112.56]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group
                    name="Object_76"
                    position={[259.071, -185.691, -70.699]}
                  >
                    <mesh
                      name="motor4_metal_frio_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor4_metal_frio_0.geometry}
                      material={materials.metal_frio}
                    />
                    <mesh
                      name="motor4_metal_alumi_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor4_metal_alumi_0.geometry}
                      material={materials.metal_alumi}
                    />
                    <mesh
                      name="motor4_metalic_dark_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor4_metalic_dark_0.geometry}
                      material={materials.metalic_dark}
                    />
                    <mesh
                      name="motor4_metal_neutro_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.motor4_metal_neutro_0.geometry}
                      material={materials.metal_neutro}
                    />
                  </group>
                </group>
                <group
                  name="pantallas"
                  position={[0.092, 73.322, -131.141]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.528, 1.161, 1]}
                >
                  <group name="Object_82" position={[101.36, -12.376, -31.042]}>
                    <mesh
                      name="pantallas_pantallas_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.pantallas_pantallas_0.geometry}
                      material={materials.pantallas}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/no_mans_sky_-_radiant_pillar_bc1.glb");
